### ISSUE TITLE
Unable to build - Share latest stepper.jar file

### ISSUE THREAD

**Issue by ganesh2183** [CoreyD97/Stepper#65]
Hi @CoreyD97 

Please share or upload latest stepper.jar file in release page to use with burp suite tool. Unable to build.

**Comment by irsdl** [comment]
@CoreyD97 I think a tag needs to be added so that https://github.com/CoreyD97/Stepper/blob/master/.github/workflows/releases.yaml would build a new release.

I have implemented this similarly using a dirty method of (build==release) in https://github.com/mdsecresearch/BurpSuiteSharpener/blob/main/.github/workflows/gradle.yml

**Comment by CoreyD97** [comment]
The newest release has been published.

https://github.com/CoreyD97/Stepper/releases/tag/v1.4.3
